[infrastructure]
# This flag determines whether the results of the evaluation should be sent
# to the infrastructure orchastrator. For local execution, it should always
# be set to `false`
send_to_orchestrator = false
# This flag determines whether the last input and output files for a
# submission should be cleaned; if set to true, past results are preserved
# and the evaluation skips all problems that had already been solved
resume = false

[evaluation]
# Time limit for the solution of each instance. Overheads introduced by the
# evaluation script are already discounted, but this is not possible for
# overheads in the submission web service and latency. For this reason, the
# limit always includes some buffer time.
time_limit = 1050
# Step limit, used to avoid infinite loops
max_steps = 10
# Number of simulations to performed for every instance (used only in the
# probabilistic evaluation)
nsamples = 5
# Value of the alpha coefficient in the score function
# alpha = 0.1
# Value of the beta coefficient in the score function
# beta = 0.1
# Value of the beta coefficient in the score function
seed = 42
# Time allowed to reboot the submission container, in case it is terminated.
# This is only needed for the online evaluation platform, keep it as it
# is for local execution
reboot_time_limit = 30
